CREATE TABLE Animal(
    ID INT PRIMARY KEY,
    Weight INT NOT NULL,
)

CREATE TABLE Bird(
    ID PRIMARY KEY REFERENCES Animal(ID),
    Wingspan INT NOT NULL,
)


CREATE TABLE Fox(
    ID PRIMARY KEY REFERENCES Animal(ID),
    Color VARCHAR(7) NOT NULL,
)


CREATE TABLE Dog(
    ID PRIMARY KEY REFERENCES Animal(ID),
    Color VARCHAR(7) NOT NULL,
)

CREATE TABLE Kill(
	ID PRIMARY KEY REFERENCES Animal(ID),
	HunterID INT NOT NULL,
)

CREATE TABLE Hunter(
	ID PRIMARY KEY REFERENCES Animal(ID),
)